sudo: true
language: scala
services:
  - docker

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - name: test jdk11 2.13
      scala: 2.13.4
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test jdk8 2.13
      scala: 2.13.4
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test jdk11 2.12
      scala: 2.12.13
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: test jdk8 2.12
      scala: 2.12.13
      jdk: openjdk8
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - name: mima
      jdk: openjdk8
      script: sbt +mimaReportBinaryIssues
    - name: docs
      scala: 2.12.13
      jdk: openjdk8
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
    # run ci-release only if previous stages passed
    - stage: release
      name: release
      jdk: openjdk8
      script:
        - sbt ci-release
    - stage: release
      name: microsite
      scala: 2.12.13
      jdk: openjdk11
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.2.1
      script: sbt ++$TRAVIS_SCALA_VERSION docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
