name: fuuid
baseurl: /fuuid
description: Functional UUID's
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-M2+30-3b7b3c2c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
