name: fuuid
baseurl: /fuuid
description: Functional UUID's
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-M2+28-868b43b3-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
