name: fuuid
baseurl: /fuuid
description: Functional UUID's
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.3.0-M3+12-d5631ca5-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
